name: pesterscan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze_scripts:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download and install PowerShell Core
        run: |
          $url = 'https://github.com/PowerShell/PowerShell/releases/latest/download/PowerShell-Preview.win-x64.msi'
          $path = "$env:TEMP\PowerShell-Preview.win-x64.msi"
          Invoke-WebRequest -Uri $url -OutFile $path
          Start-Process -FilePath $path -ArgumentList "/quiet" -Wait

      - name: Run tests  
        shell: pwsh
        run: |
          Invoke-Pester -Path '/secure.tests.ps1'
